name: Build Anda Project
description: Builds an Anda project.

inputs:
  name:
    required: true
    description: The name of the project to build.
  mockConfig:
    required: true
    description: The name of the mock config to use for the build.
  extraInitRepos:
    required: false
    description: A comma-separated list of extra repositories to initialize before building the project.
  andaRepo:
    required: false
    description: The DNF repository from which you want to install anda from
  extraArgs:
    required: false
    description: Extra arguments to pass to anda

runs:
  using: "composite"
  steps:
    - name: Install DNF plugins
      shell: bash
      run: dnf5 in -y dnf-plugins-core
    - name: Add repository
      shell: bash
      if: inputs.andaRepo
      run: dnf5 config-manager addrepo --from-repofile=${{ inputs.andaRepo }}
    - name: Add extra repositories
      shell: bash
      if: inputs.extraInitRepos
      run: |
        # separate by comma and add each repo
        IFS=',' read -ra EXTRA_REPOS <<< "${{ inputs.extraInitRepos }}"
        for repo in "${EXTRA_REPOS[@]}"; do
          dnf5 config-manager addrepo --from-repofile=$repo
        done
    - name: Install packages
      shell: bash
      run: dnf5 in -y createrepo_c git gcc curl wget anda
    - uses: actions/checkout@v3
      with:
        submodules: "recursive"
        fetch-depth: 1
    - name: Set up git repository
      shell: bash
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Build with Anda
      shell: bash
      run: anda build ${{ inputs.name }} --package rpm -c ${{ inputs.mockConfig }} ${{ inputs.extraArgs }}
